### ISSUE TITLE
Retrive Password from device.password

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#248]
Hi ,
I want to run a Python snippet service .In this i want the device parameters .One of them is device.password.When i run this , i am getting the output in bytes.i converted it using the decoder but still i do not get the original password.Can you tell me a way out ????

device1=str(device.ip_address)
username=(device.username)
extra_args = device.get_properties()
extra_args["password"] = device.password
password = extra_args.get("password")
result = password.decode("utf-8")
results["result"] = result

The result here always show the decoded bytes password which is not the one i entered in the device.

**Comment by afourmy** [comment]
If the password is obfuscated with b64 you can deobfuscate it with `b64decode`. In a production deployment, passwords are encrypted with Fernet and there is no way to get the device password from a python snippet service: this is a security measure, otherwise any user could just print it in the logs and see it in cleartext. So whatever your use-case it, you shouldn't need to use the device password from a python snippet service.
