### ISSUE TITLE
Log to custom logger causing error

### ISSUE THREAD

**Issue by konstant1ne** [eNMS-automation/eNMS#269]
calling log() function from python snippet service with custom logger (logger='xxxxxx' parameter) is causing following error:

2020-07-01 15:50:23.649302 - info - USER - SERVICE Log Start - DEVICE xxxxxxx - STARTING
2020-07-01 15:50:23.653251 - info - USER - SERVICE Log Start - Execution error(line 309): AttributeError: 'NoneType' object has no attribute 'get'

Logger configuration verified .

**Comment by afourmy** [comment]
Did you configure the custom logger here: https://github.com/eNMS-automation/eNMS/blob/master/setup/settings.json#L39-L49 to tell eNMS whether it should log to changelog / service log by default ?
I made a change so that it doesn't fail but default to an empty dict if there's nothing there, but you should still have something like that in your settings.json file

**Comment by konstant1ne** [comment]
I believe the settings.json came with the release as it matches exactly (logging section in particular) to settings.json in GIT. Which is a bit confusing. Custom loggers are defined in logging.json and not in settings.json. eNMS/controller/base.py code seems to be looking in the wrong settings data set?

```
    def log(self, severity, content, user=None, change_log=True, logger="root"):
        logger_settings = self.settings["logging"]["loggers"].get(logger)
```

**Comment by afourmy** [comment]
I updated the settings so that everything is in https://github.com/eNMS-automation/eNMS/blob/master/setup/logging.json now
Can you see if it works for you next time you pull my changes?
