### ISSUE TITLE
Why one service, one table?

### ISSUE THREAD

**Issue by rwlrwlrwlrwl** [eNMS-automation/eNMS#293]
Some confusion about design, hope to be answered!
1. Each service generates a table. When there are many services, there will be many tables. Why was it designed like this?
2. Is it possible to dynamically create customer-defined services? (Do not restart the web service)

**Comment by afourmy** [comment]
1. each service generates a row, not a table. Tables can scale to 10s of thousands of rows with server-side processing so the number of rows is not an issue. Besides, by default, the service table is in "hierarchical display" mode: only top-level workflows and standalone services are displayed, i.e very few.
2. no, the app must be reloaded when new services are added to the /services folder for the table to be created in the db.

**Comment by rwlrwlrwlrwl** [comment]
Thank you very much for your reply!
I mean service type, not service. I am thinking whether the service type can be divided into smaller granularity by business, such as configure_bgp.py in the example, I can also add configure_vlan.py, configure_access_port.py, etc.
Then when there are many service types, there will be many tables.
From this perspective, what is your suggestion?
thanks!

**Comment by afourmy** [comment]
From a database perspective, there is no scalability issue: the database can have as many tables as you need. As far as the UI is concerned, that doesn't seem like much of a problem either given that the "Service type" select list comes with a search box in both the service table and the workflow builder, it can filter the list almost instantaneously.
It was designed like this because a service can have as many custom fields as you want (text, boolean, select list, etc) and we need to store these values in the database, which implies that we have to create a subclass of the service table with the associated custom rows.
