### ISSUE TITLE
eNMS login issue

### ISSUE THREAD

**Issue by dd1245** [eNMS-automation/eNMS#298]
Hi. I've done a new install today on Ubuntu 20.04.1 LTS.

Setup for production mode with PostgresSQL and the gunicorn.py starts fine. tested the DB access and export commands issues as required.

I can hit port 5000, but when trying to login as admin/admin I get 403 access denied page.

The security.log shows "WARNING  Authentication failed for user 'admin'"

Is there a new password for this? if not how can I determine the issue here?

Thanks

**Comment by afourmy** [comment]
There is no new password, the admin credentials should be "admin" / "admin" by default.
Just tried with pgsql and it works in my environment. I don't know why it doesn't in yours.
In the db, the password field for the "admin" user should contain an argon2 hash, make sure that it is the case. I cannot tell you what the hash should be because a random salt is generated.

**Comment by dd1245** [comment]
Ok. I wonder if the 403 is masking a different problem.

When does the pgsql db get populated?

**Comment by afourmy** [comment]
here: https://github.com/eNMS-automation/eNMS/blob/master/eNMS/controller/base.py#L120-L126
there should be no admin user when you run the app for the first time.
admin password is set here: https://github.com/eNMS-automation/eNMS/blob/master/eNMS/controller/base.py#L153-L156

**Comment by dd1245** [comment]
Thanks

**Comment by dd1245** [comment]
A local issue clearly. I've resolved this now. Thanks for your help.
