### ISSUE TITLE
Device Credentials Not Found

### ISSUE THREAD

**Issue by adaker1985** [eNMS-automation/eNMS#314]
I just spun up a POC lab for eNMS and Hashicorp Vault.  The first task I am trying to accomplish is backing up a FortiGate with with netmiko.  I have a credential call "TestFortiGate" and it successfully save the password to the vault.  I then created a device called "TestFortiGate".  When I create my service and try to run it, I get the following result:

result | : | No matching credentials found for DEVICE 'TestFortiGate'

I do not  see where I can add device credentials.  What am I missing?

**Comment by afourmy** [comment]
In the credential object, there is a "Devices" field which lets you select a pool (i.e group of devices) that the credentials will be used for. This is not documented yet because you're on the master branch and it hasn't been officially released; last official version is eNMS 3.22.3 (https://github.com/eNMS-automation/eNMS/releases)

We'll probably add another "Credentials" field in the device panel soon, so you can set a credential directly on the device, without needing to create a pool beforehand.
