### ISSUE TITLE
eNMS does not display large configuration files in the UI

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#326]
I have several routers with over 30,000 lines of configuration. When displaying the configuration file in the UI I can only see about 3500 lines. When I search for text that is above 3500 it does not return the string. I checked the configuration file for the device on the server and it does have the complete configuration.

**Comment by afourmy** [comment]
Just tested a configuration with 50 000 lines, it's slow but it works fine, everything is displayed. If you want to search a large conf, you must use the configuration search field of the configuration table so that it only displays the lines that match, not the search mechanism of the "Network Data" panel, displaying and searching that much data in JS isn't efficient.
If you're sure there's a problem with eNMS, please provide the exact steps to reproduce the problem you're having.
